<p style="font-size:24px; font-weight:bold;">Data Cleaning Start from Here</p>
Customers Table

In [ ]:
import os
import pandas as pd

files = sorted(os.listdir())
print('Files in folder:')
for file in files:
    print('-', file)
customers_df = pd.read_csv('olist_customers_dataset.csv')

print('\nFirst 5 rows of olist_customers_dataset.csv:')
display(customers_df.head(10))

print('\nShape:', customers_df.shape)
print('\nColumns:')
print(customers_df.columns.tolist())

print('\nDataset info:')
customers_df.info()

Files in folder:
- Cleaning_Olist_files.ipynb
- olist_customers_dataset.csv
- olist_geolocation_dataset.csv
- olist_order_items_dataset.csv
- olist_order_payments_dataset.csv
- olist_order_reviews_dataset.csv
- olist_orders_dataset.csv
- olist_products_dataset.csv
- olist_sellers_dataset.csv
- product_category_name_translation.csv

First 5 rows of olist_customers_dataset.csv:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG

Shape: (99441, 5)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [5]:
customers_df.duplicated().sum()

np.int64(0)

In [9]:
print("Total unique customer_id:", customers_df['customer_id'].nunique())
print("Total unique customer_unique_id:", customers_df['customer_unique_id'].nunique())

Total unique customer_id: 99441
Total unique customer_unique_id: 96096

In [7]:
customers_df['customer_id'].nunique()
customers_df.shape[0]

99441

In [8]:
print("Unique customer_id:", customers_df['customer_id'].nunique())
print("Total rows:", customers_df.shape[0])

Unique customer_id: 99441
Total rows: 99441

In [12]:
summary = pd.DataFrame({
    'column': ['customer_city', 'customer_state'],
    'total_values': [
        customers_df['customer_city'].count(),
        customers_df['customer_state'].count()
    ],
    'unique_values': [
        customers_df['customer_city'].nunique(),
        customers_df['customer_state'].nunique()
    ]
})

summary

           column  total_values  unique_values
0   customer_city         99441           4119
1  customer_state         99441             27

In [13]:
# 1. Check if any city name has uppercase letters
uppercase_cities = customers_df[
    customers_df['customer_city'].str.contains(r'[A-Z]', regex=True, na=False)
]['customer_city'].drop_duplicates().sort_values()

print("Cities with uppercase letters:", len(uppercase_cities))
display(uppercase_cities)

Cities with uppercase letters: 0

Series([], Name: customer_city, dtype: str)

In [14]:
# 2. Check if any city name has messy/special characters
messy_cities = customers_df[
    customers_df['customer_city'].str.contains(r'[^a-z\s]', regex=True, na=False)
]['customer_city'].drop_duplicates().sort_values()

print("Cities with special/messy characters:", len(messy_cities))
display(messy_cities)

Cities with special/messy characters: 53

12904         alta floresta d'oeste
48321              alvorada d'oeste
23408             aparecida d'oeste
4055                arraial d'ajuda
40634          bandeirantes d'oeste
21736                biritiba-mirim
9641                    ceara-mirim
3064                     cipo-guacu
76273             conquista d'oeste
8426               diamante d'oeste
1342                   dias d'avila
2162                     embu-guacu
36974                   entre-ijuis
69301               estrela d'oeste
27417         figueiropolis d'oeste
26737    governador dix-sept rosado
3521                  guajara-mirim
19572                    guarda-mor
16360                herval d'oeste
49812                   igarape-acu
74015                  igarape-miri
5705              itapejara d'oeste
29129            itaporanga d'ajuda
4486                      ji-parana
83079                  lagoa d'anta
18087            machadinho d'oeste
39116                    mae d'agua
5948               mirassol d'oeste
435                      mogi-guacu
81253                    mogi-mirim
23254                  nao-me-toque
5400       nova brasilandia d'oeste
40416        olho d'agua das cunhas
20916        olho d'agua das flores
98331                  olhos d'agua
58805              palmeira d'oeste
1362                  pariquera-acu
39860                    pau d'arco
64231                perola d'oeste
53219                  pingo-d'agua
6333         quilometro 14 do mutum
19674         rancho alegre d'oeste
2801          santa barbara d'oeste
23368           santa clara d'oeste
14571            santa rita d'oeste
8061             sao joao d'alianca
80566             sao jorge d'oeste
10835                 sapucai-mirim
16733                 tanque d'arca
92266                      tome-acu
227                       varre-sai
15379                     xangri-la
2098                    xique-xique
Name: customer_city, dtype: str

In [15]:
print("Any uppercase in customer_city:",
      customers_df['customer_city'].str.contains(r'[A-Z]', regex=True, na=False).any())

print("Any special characters in customer_city:",
      customers_df['customer_city'].str.contains(r'[^a-z\s]', regex=True, na=False).any())

Any uppercase in customer_city: False
Any special characters in customer_city: True

In [17]:
customers_df['customer_city'] = customers_df['customer_city'].str.strip().str.replace(r'\s+', ' ', regex=True)
customers_df['customer_state'] = customers_df['customer_state'].str.strip().str.replace(r'\s+', ' ', regex=True)
customers_df[['customer_city', 'customer_state']].head()

           customer_city customer_state
0                 franca             SP
1  sao bernardo do campo             SP
2              sao paulo             SP
3        mogi das cruzes             SP
4               campinas             SP

In [18]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

customers_df.to_csv(os.path.join(save_path, "customers.csv"), index=False)

print("Cleaned file saved as customers.csv")

Cleaned file saved as customers.csv

<p style="font-size:24px; font-weight:bold;">Geolocation</p>

In [3]:
import pandas as pd

geolocation_df = pd.read_csv("olist_geolocation_dataset.csv")

print("First 10 rows of olist_geolocation_dataset.csv:")
display(geolocation_df.head(10))

print("\nShape:", geolocation_df.shape)
print("\nColumns:")
print(geolocation_df.columns.tolist())

print("\nDataset info:")
geolocation_df.info()
geolocation_df.duplicated().sum()

First 10 rows of olist_geolocation_dataset.csv:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
5,1012,-23.547762,-46.635361,são paulo,SP
6,1047,-23.546273,-46.641225,sao paulo,SP
7,1013,-23.546923,-46.634264,sao paulo,SP
8,1029,-23.543769,-46.634278,sao paulo,SP
9,1011,-23.547640,-46.636032,sao paulo,SP

Shape: (1000163, 5)

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

np.int64(261831)

In [4]:
print("Missing values in geolocation_city:", geolocation_df['geolocation_city'].isnull().sum())
print("Missing values in geolocation_state:", geolocation_df['geolocation_state'].isnull().sum())

uppercase_city = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(r'[A-Z]', regex=True, na=False)
]['geolocation_city'].drop_duplicates().sort_values()

print("\nCities with uppercase letters:", len(uppercase_city))
display(uppercase_city)

weird_city = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(r'[^a-z\\s]', regex=True, na=False)
]['geolocation_city'].drop_duplicates().sort_values()

print("\nCities with weird characters:", len(weird_city))
display(weird_city)

not_upper_state = geolocation_df[
    ~geolocation_df['geolocation_state'].str.fullmatch(r'[A-Z]+', na=False)
]['geolocation_state'].drop_duplicates().sort_values()

print("\nStates that are not fully uppercase:", len(not_upper_state))
display(not_upper_state)

weird_state = geolocation_df[
    geolocation_df['geolocation_state'].str.contains(r'[^A-Z]', regex=True, na=False)
]['geolocation_state'].drop_duplicates().sort_values()

print("\nStates with weird characters:", len(weird_state))
display(weird_state)

Missing values in geolocation_city: 0
Missing values in geolocation_state: 0

Cities with uppercase letters: 0

Series([], Name: geolocation_city, dtype: str)

Cities with weird characters: 5016

851430              * cidade
525385    ...arraial do cabo
896733        4o. centenario
896977         4º centenario
804356       abadia de goias
                 ...
999612                 áurea
889778                ângulo
695823         érico cardoso
769309                óbidos
394381                  óleo
Name: geolocation_city, Length: 5016, dtype: str

States that are not fully uppercase: 0

Series([], Name: geolocation_state, dtype: str)

States with weird characters: 0

Series([], Name: geolocation_state, dtype: str)

In [5]:
messy_city = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(
        r'(^\*|^\.\.\.|[0-9]|[;:"|])',
        regex=True,
        na=False
    )
]['geolocation_city'].drop_duplicates().sort_values()

print("Clearly messy city names:", len(messy_city))
display(messy_city)

C:\Users\England\AppData\Local\Temp\ipykernel_15700\3967762517.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

Clearly messy city names: 11

851430                           * cidade
525385                 ...arraial do cabo
896733                     4o. centenario
896977                      4º centenario
977813                        colonia z-3
977775                        colônia z-3
900755               florian&oacute;polis
823386           lambari d%26apos%3boeste
538905             quilometro 14 do mutum
786179                     riacho fundo 2
377210    são joão do pau d%26apos%3balho
Name: geolocation_city, dtype: str

In [6]:
geolocation_df[
    geolocation_df['geolocation_city'].str.contains(
        r'(^\*|^\.\.\.|[0-9]|[;:"|])',
        regex=True,
        na=False
    )
][['geolocation_city']].drop_duplicates().sort_values(by='geolocation_city')

C:\Users\England\AppData\Local\Temp\ipykernel_15700\853141053.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

                       geolocation_city
851430                         * cidade
525385               ...arraial do cabo
896733                   4o. centenario
896977                    4º centenario
977813                      colonia z-3
977775                      colônia z-3
900755             florian&oacute;polis
823386         lambari d%26apos%3boeste
538905           quilometro 14 do mutum
786179                   riacho fundo 2
377210  são joão do pau d%26apos%3balho

In [7]:
geolocation_df['geolocation_city'] = geolocation_df['geolocation_city'].replace({
    '* cidade': 'cidade',
    '...arraial do cabo': 'arraial do cabo',
    '4o. centenario': 'centenario',
    '4º centenario': 'centenario',
    'colonia z-3': 'colonia z 3',
    'colônia z-3': 'colônia z 3',
    'florian&oacute;polis': 'florianópolis',
    'lambari d%26apos%3boeste': "lambari d'oeste",
    'quilometro 14 do mutum': 'mutum',
    'riacho fundo ': 'riacho fundo'
})

In [8]:
geolocation_df.loc[
    geolocation_df['geolocation_city'].isin([
        'cidade',
        'arraial do cabo',
        'centenario',
        'colonia z 3',
        'colônia z 3',
        'florianópolis',
        "lambari d'oeste",
        'mutum',
        'riacho fundo'
    ]),
    ['geolocation_city']
].drop_duplicates().sort_values(by='geolocation_city')

       geolocation_city
521341  arraial do cabo
818651       centenario
851430           cidade
977813      colonia z 3
977775      colônia z 3
899991    florianópolis
822794  lambari d'oeste
538905            mutum
786072     riacho fundo

In [10]:
remaining_messy_city = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(
        r'(^\*|^\.\.\.|[0-9]|[;:"|]|&|%26|apos)',
        regex=True,
        na=False
    )
]['geolocation_city'].drop_duplicates().sort_values()

print("Remaining messy city names:", len(remaining_messy_city))
display(remaining_messy_city)

C:\Users\England\AppData\Local\Temp\ipykernel_15700\2353617064.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

Remaining messy city names: 7

977813                        colonia z 3
977775                        colônia z 3
758401                             raposa
514365                             raposo
582329                            raposos
786179                     riacho fundo 2
377210    são joão do pau d%26apos%3balho
Name: geolocation_city, dtype: str

In [ ]:
import re

geolocation_df['geolocation_city'] = geolocation_df['geolocation_city'].replace({
    'colonia z 3': 'colônia',
    'colônia z 3': 'colônia',

    'old_wrong_value': 'São João'
})

geolocation_df['geolocation_city'] = (
    geolocation_df['geolocation_city']
    .str.replace(r'\b\w*\d+\w*\b', '', regex=True)   # remove words with numbers
    .str.replace(r'\s+', ' ', regex=True)            # remove extra spaces
    .str.strip()
)

In [12]:
geolocation_df['geolocation_city'].drop_duplicates().sort_values()

804356        abadia de goias
650451    abadia dos dourados
792364              abadiania
792411              abadiânia
598309                 abaete
                 ...
999612                  áurea
889778                 ângulo
695823          érico cardoso
769309                 óbidos
394381                   óleo
Name: geolocation_city, Length: 8000, dtype: str

In [13]:
remaining_messy_city = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(
        r'(^\*|^\.\.\.|[;:"|&%]|apos|\b\d+\b)',
        regex=True,
        na=False
    )
]['geolocation_city'].drop_duplicates().sort_values()

print("Remaining messy city names:", len(remaining_messy_city))
display(remaining_messy_city)

C:\Users\England\AppData\Local\Temp\ipykernel_15700\1530839784.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

Remaining messy city names: 4

758401                 raposa
514365                 raposo
582329                raposos
377210    são joão do pau d%%
Name: geolocation_city, dtype: str

In [ ]:
geolocation_df.loc[
    geolocation_df['geolocation_city'].str.contains(r'sao joao', case=False, na=False),
    'geolocation_city'
] = 'São João do Pau'

geolocation_df['geolocation_city'] = (
    geolocation_df['geolocation_city']
    .str.replace(r"[^A-Za-zÀ-ÿ\s]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [15]:
geolocation_df[
    geolocation_df['geolocation_city'].str.contains('São João', na=False)
]['geolocation_city'].drop_duplicates()

319699    São João do Pau
Name: geolocation_city, dtype: str

In [16]:
geolocation_df.loc[
    geolocation_df['geolocation_city'].str.contains(r'^repo', case=False, na=False),
    'geolocation_city'
] = 'Raposos'

In [17]:
geolocation_df[
    geolocation_df['geolocation_city'].str.contains(r'^Raposos$', case=False, na=False)
]['geolocation_city'].value_counts()

geolocation_city
raposos    83
Name: count, dtype: int64

In [18]:
remaining_messy_city = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(
        r'(^\*|^\.\.\.|[0-9]|[;:"|&%]|apos)',
        regex=True,
        na=False
    )
]['geolocation_city'].drop_duplicates().sort_values()

print("Remaining messy city names:", len(remaining_messy_city))
display(remaining_messy_city)

C:\Users\England\AppData\Local\Temp\ipykernel_15700\3775093444.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

Remaining messy city names: 3

758401     raposa
514365     raposo
582329    raposos
Name: geolocation_city, dtype: str

In [19]:
extra_space_city = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(r'^\s|\s$|\s{2,}', regex=True, na=False)
]['geolocation_city'].drop_duplicates().sort_values()

print("Cities with extra spaces:", len(extra_space_city))
display(extra_space_city)

Cities with extra spaces: 0

Series([], Name: geolocation_city, dtype: str)

In [20]:
remaining_messy_city = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(
        r'(^\*|^\.\.\.|[0-9]|[;:"|&%]|apos)',
        regex=True,
        na=False
    )
]['geolocation_city'].drop_duplicates().sort_values()

print("Remaining messy city names:", len(remaining_messy_city))
display(remaining_messy_city)

C:\Users\England\AppData\Local\Temp\ipykernel_15700\3775093444.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

Remaining messy city names: 3

758401     raposa
514365     raposo
582329    raposos
Name: geolocation_city, dtype: str

In [21]:
print("Any messy city values left:",
      geolocation_df['geolocation_city'].str.contains(
          r'(^\*|^\.\.\.|[0-9]|[;:"|&%]|apos)',
          regex=True,
          na=False
      ).any())

print("Any extra spaces left:",
      geolocation_df['geolocation_city'].str.contains(
          r'^\s|\s$|\s{2,}',
          regex=True,
          na=False
      ).any())

C:\Users\England\AppData\Local\Temp\ipykernel_15700\1476665780.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

Any messy city values left: True
Any extra spaces left: False

In [22]:
messy_city_list = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(
        r'(^\*|^\.\.\.|[0-9]|[;:"|&%]|apos)',
        regex=True,
        na=False
    )
]['geolocation_city'].drop_duplicates().sort_values()

print("Messy city values:")
display(messy_city_list)

C:\Users\England\AppData\Local\Temp\ipykernel_15700\2774481349.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

Messy city values:

758401     raposa
514365     raposo
582329    raposos
Name: geolocation_city, dtype: str

In [23]:
geolocation_df[
    geolocation_df['geolocation_city'].str.contains(
        r'(^\*|^\.\.\.|[0-9]|[;:"|&%]|apos)',
        regex=True,
        na=False
    )
][['geolocation_city']].drop_duplicates().sort_values(by='geolocation_city')

C:\Users\England\AppData\Local\Temp\ipykernel_15700\3187761413.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(

       geolocation_city
758401           raposa
514365           raposo
582329          raposos

In [24]:
geolocation_df.loc[
    geolocation_df['geolocation_city'].str.contains(r'^(repo|rapo)', case=False, na=False),
    'geolocation_city'
] = 'Raposos'

C:\Users\England\AppData\Local\Temp\ipykernel_15700\3106523771.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  geolocation_df['geolocation_city'].str.contains(r'^(repo|rapo)', case=False, na=False),

In [25]:
geolocation_df[
    geolocation_df['geolocation_city'] == 'Raposos'
]['geolocation_city'].value_counts()

geolocation_city
Raposos    99
Name: count, dtype: int64

In [26]:
city_counts = geolocation_df['geolocation_city'].value_counts().reset_index()
city_counts.columns = ['geolocation_city', 'count']
city_counts

                geolocation_city   count
0                      sao paulo  135801
1                 rio de janeiro   62151
2                 belo horizonte   27805
3                      são paulo   24918
4                       curitiba   16593
...                          ...     ...
7905          são josé do herval       1
7906  almirante tamandaré do sul       1
7907                são valentim       1
7908                três arroios       1
7909                     ciríaco       1

[7910 rows x 2 columns]

In [27]:
geolocation_df.loc[
    geolocation_df['geolocation_city'].str.contains(r's[^a-zA-Z]*a[^a-zA-Z]*o.*p[^a-zA-Z]*a[^a-zA-Z]*u[^a-zA-Z]*l[^a-zA-Z]*o', case=False, na=False),
    'geolocation_city'
] = 'São Paulo'

In [28]:
geolocation_df[geolocation_df['geolocation_city'] == 'São Paulo'][['geolocation_city']]

       geolocation_city
0             São Paulo
1             São Paulo
2             São Paulo
3             São Paulo
4             São Paulo
...                 ...
989983        São Paulo
989990        São Paulo
989994        São Paulo
989996        São Paulo
990007        São Paulo

[135843 rows x 1 columns]

In [29]:
# Replace any city containing some form of "macae" / "macaé" with "Macaé"
geolocation_df.loc[
    geolocation_df['geolocation_city'].str.contains(
        r'm[^a-zA-ZÀ-ÿ]*a[^a-zA-ZÀ-ÿ]*c[^a-zA-ZÀ-ÿ]*a[^a-zA-ZÀ-ÿ]*[eé]',
        case=False,
        na=False
    ),
    'geolocation_city'
] = 'Macaé'

In [30]:
geolocation_df[geolocation_df['geolocation_city'] == 'Macaé'][['geolocation_city']].head()

       geolocation_city
508585            Macaé
508586            Macaé
508587            Macaé
508588            Macaé
508589            Macaé

In [32]:
geolocation_df.loc[
    geolocation_df['geolocation_city'].str.contains(
        r'b[^a-zA-ZÀ-ÿ]*i[^a-zA-ZÀ-ÿ]*r[^a-zA-ZÀ-ÿ]*i[^a-zA-ZÀ-ÿ]*g[^a-zA-ZÀ-ÿ]*u[^a-zA-ZÀ-ÿ]*i',
        case=False,
        na=False
    ),
    'geolocation_city'
] = 'Birigui'
print("Cities containing some form of 'birigui':")

Cities containing some form of 'birigui':

In [33]:
import re
import html
import unicodedata
from urllib.parse import unquote

def normalize_city(text):
    if pd.isna(text):
        return text
    
    text = str(text).strip().lower()
    
    text = html.unescape(text)
    text = unquote(text)
    
    text = re.sub(r'^[\.\*\-_,;:]+', '', text)
    
    text = re.sub(r"[^a-zA-ZÀ-ÿ\s]", " ", text)
    
    text = re.sub(r'\b\w*\d+\w*\b', ' ', text)
    
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

def remove_accents(text):
    if pd.isna(text):
        return text
    return ''.join(
        ch for ch in unicodedata.normalize('NFKD', text)
        if not unicodedata.combining(ch)
    )

def pt_title(text):
    if pd.isna(text):
        return text
    
    small_words = {'de', 'da', 'do', 'das', 'dos', 'e'}
    words = text.split()
    
    result = []
    for i, word in enumerate(words):
        if i > 0 and word in small_words:
            result.append(word)
        else:
            result.append(word.capitalize())
    return ' '.join(result)

geolocation_df['city_clean_temp'] = geolocation_df['geolocation_city'].apply(normalize_city)

geolocation_df['city_key'] = geolocation_df['city_clean_temp'].apply(remove_accents)

canonical_map = (
    geolocation_df.groupby('city_key')['city_clean_temp']
    .agg(lambda x: x.value_counts().index[0])
    .to_dict()
)

geolocation_df['geolocation_city_cleaned'] = geolocation_df['city_key'].map(canonical_map)

geolocation_df['geolocation_city_cleaned'] = geolocation_df['geolocation_city_cleaned'].apply(pt_title)


geolocation_df['geolocation_city'] = geolocation_df['geolocation_city_cleaned']

geolocation_df.drop(columns=['city_clean_temp', 'city_key', 'geolocation_city_cleaned'], inplace=True)

print("City names cleaned.")

City names cleaned.

In [34]:
remaining = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(r'[^A-Za-zÀ-ÿ\s]', regex=True, na=False)
]['geolocation_city'].drop_duplicates().sort_values()

display(remaining)

Series([], Name: geolocation_city, dtype: str)

In [35]:
remaining = geolocation_df[
    geolocation_df['geolocation_city'].str.contains(r'[^A-Za-zÀ-ÿ\s]', regex=True, na=False)
]['geolocation_city'].drop_duplicates().sort_values()

if remaining.empty:
    print("No messy city values found.")
else:
    print("Messy city values found:")
    display(remaining)

No messy city values found.

In [36]:
print("Missing values:\n")
print(geolocation_df.isnull().sum())

Missing values:

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [38]:
import pandas as pd

customers_df = pd.read_csv("olist_customers_dataset.csv")

In [39]:
import pandas as pd
import re
import html
import unicodedata
from urllib.parse import unquote

customers_df = pd.read_csv("olist_customers_dataset.csv")

def normalize_city(text):
    if pd.isna(text):
        return text
    
    text = str(text).strip().lower()
    text = html.unescape(text)
    text = unquote(text)
    text = re.sub(r'^[\.\*\-_,;:]+', '', text)
    text = re.sub(r"[^a-zA-ZÀ-ÿ\s]", " ", text)
    text = re.sub(r'\b\w*\d+\w*\b', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def remove_accents(text):
    if pd.isna(text):
        return text
    return ''.join(
        ch for ch in unicodedata.normalize('NFKD', text)
        if not unicodedata.combining(ch)
    )

def pt_title(text):
    if pd.isna(text):
        return text
    
    small_words = {'de', 'da', 'do', 'das', 'dos', 'e'}
    words = text.split()
    
    result = []
    for i, word in enumerate(words):
        if i > 0 and word in small_words:
            result.append(word)
        else:
            result.append(word.capitalize())
    return ' '.join(result)

customers_df['city_clean_temp'] = customers_df['customer_city'].apply(normalize_city)
customers_df['city_key'] = customers_df['city_clean_temp'].apply(remove_accents)

canonical_map = (
    customers_df.groupby('city_key')['city_clean_temp']
    .agg(lambda x: x.value_counts().index[0])
    .to_dict()
)

customers_df['customer_city'] = customers_df['city_key'].map(canonical_map).apply(pt_title)

customers_df.drop(columns=['city_clean_temp', 'city_key'], inplace=True)

print("customer_city cleaned successfully.")

customer_city cleaned successfully.

In [40]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

customers_df.to_csv(os.path.join(save_path, "customers.csv"), index=False)

print("Saved successfully as customers.csv")

Saved successfully as customers.csv

In [41]:
print("Missing values:\n")
print(geolocation_df.isnull().sum())

print("\nDuplicate rows:", geolocation_df.duplicated().sum())

print("\nAny messy city values left:",
      geolocation_df['geolocation_city'].str.contains(
          r'[^A-Za-zÀ-ÿ\s]',
          regex=True,
          na=False
      ).any())

print("\nAny extra spaces in city:",
      geolocation_df['geolocation_city'].str.contains(
          r'^\s|\s$|\s{2,}',
          regex=True,
          na=False
      ).any())

print("\nAny state not uppercase:",
      (~geolocation_df['geolocation_state'].str.fullmatch(r'[A-Z]{2}', na=False)).any())

Missing values:

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Duplicate rows: 279560

Any messy city values left: False

Any extra spaces in city: False

Any state not uppercase: False

In [42]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

geolocation_df.to_csv(os.path.join(save_path, "geolocation.csv"), index=False)

print("Saved successfully as geolocation.csv")

Saved successfully as geolocation.csv

<p style="font-size:24px; font-weight:bold;">Olist Order Items</p>

In [13]:
import pandas as pd

order_items_df = pd.read_csv("olist_order_items_dataset.csv")

print("First 10 rows of olist_order_items_dataset.csv:")
display(order_items_df.head(10))

print("\nShape:", order_items_df.shape)
print("\nColumns:")
print(order_items_df.columns.tolist())

print("\nDataset info:")
order_items_df.info()

First 10 rows of olist_order_items_dataset.csv:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40

Shape: (112650, 7)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [2]:
import pandas as pd

order_items_df = pd.read_csv("olist_order_items_dataset.csv")

unique_counts = order_items_df.nunique()
print(unique_counts)

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

In [3]:
unique_counts = order_items_df.nunique().reset_index()
unique_counts.columns = ['column', 'unique_values']
unique_counts

                column  unique_values
0             order_id          98666
1        order_item_id             21
2           product_id          32951
3            seller_id           3095
4  shipping_limit_date          93318
5                price           5968
6        freight_value           6999

In [ ]:
import pandas as pd

order_items_df = pd.read_csv("olist_order_items_dataset.csv")

dt = pd.to_datetime(order_items_df['shipping_limit_date'], errors='coerce')

order_items_df['shipping_limit_date'] = dt.dt.date

order_items_df['shipping_limit_time'] = dt.dt.strftime('%I:%M %p')

In [15]:
order_items_df.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,shipping_limit_time
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19,58.90,13.29,09:45 AM
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03,239.90,19.93,11:05 AM
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18,199.00,17.87,02:48 PM
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15,12.99,12.79,10:10 AM
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13,199.90,18.14,01:57 PM
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23,21.90,12.69,03:55 AM
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14,19.90,11.85,12:10 PM
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10,810.00,70.75,12:30 PM
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26,145.95,11.65,06:31 PM
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06,53.99,11.40,02:10 PM

In [16]:
import pandas as pd
import numpy as np

print("Dtypes:")
print(order_items_df.dtypes)

order_items_df['price_numeric'] = pd.to_numeric(order_items_df['price'], errors='coerce')
order_items_df['freight_value_numeric'] = pd.to_numeric(order_items_df['freight_value'], errors='coerce')

print("\nNon-numeric price rows:", order_items_df['price_numeric'].isna().sum())
print("Non-numeric freight_value rows:", order_items_df['freight_value_numeric'].isna().sum())

date_check = pd.to_datetime(order_items_df['shipping_limit_date'], errors='coerce')
print("\nInvalid shipping_limit_date rows:", date_check.isna().sum())

time_check = order_items_df['shipping_limit_time'].astype(str).str.fullmatch(r'(0[1-9]|1[0-2]):[0-5][0-9] (AM|PM)')
print("Invalid shipping_limit_time rows:", (~time_check.fillna(False)).sum())

bad_rows = order_items_df[
    order_items_df['price_numeric'].isna() |
    order_items_df['freight_value_numeric'].isna() |
    date_check.isna() |
    (~time_check.fillna(False))
]

print("\nTotal rows with format problems:", len(bad_rows))
bad_rows.head(10)

Dtypes:
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date     object
price                  float64
freight_value          float64
shipping_limit_time        str
dtype: object

Non-numeric price rows: 0
Non-numeric freight_value rows: 0

Invalid shipping_limit_date rows: 0
Invalid shipping_limit_time rows: 0

Total rows with format problems: 0

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, shipping_limit_time, price_numeric, freight_value_numeric]
Index: []

In [ ]:
order_items_df['shipping_limit_date'] = pd.to_datetime(
    order_items_df['shipping_limit_date'],
    errors='coerce'
).dt.date

order_items_df['shipping_limit_time'] = pd.to_datetime(
    order_items_df['shipping_limit_time'],
    format='%I:%M %p',
    errors='coerce'
).dt.strftime('%I:%M %p')

print("Invalid shipping_limit_date:", order_items_df['shipping_limit_date'].isna().sum())
print("Invalid shipping_limit_time:", order_items_df['shipping_limit_time'].isna().sum())

Invalid shipping_limit_date: 0
Invalid shipping_limit_time: 0

In [18]:
order_items_df[
    order_items_df['shipping_limit_date'].isna() |
    order_items_df['shipping_limit_time'].isna()
].head(10)

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, shipping_limit_time, price_numeric, freight_value_numeric]
Index: []

In [19]:
summary = pd.DataFrame({
    'column': order_items_df.columns,
    'dtype': order_items_df.dtypes.values,
    'missing_values': order_items_df.isnull().sum().values,
    'unique_values': order_items_df.nunique().values
})

summary

                  column    dtype  missing_values  unique_values
0               order_id      str               0          98666
1          order_item_id    int64               0             21
2             product_id      str               0          32951
3              seller_id      str               0           3095
4    shipping_limit_date   object               0            555
5                  price  float64               0           5968
6          freight_value  float64               0           6999
7    shipping_limit_time      str               0           1427
8          price_numeric  float64               0           5968
9  freight_value_numeric  float64               0           6999

In [8]:
import pandas as pd

order_items_df = pd.read_csv("olist_order_items_dataset.csv")

# Parse datetime
dt = pd.to_datetime(order_items_df['shipping_limit_date'], errors='coerce')

# Keep date only
order_items_df['shipping_limit_date'] = dt.dt.date

# Create AM/PM time
order_items_df['shipping_limit_time'] = dt.dt.strftime('%I:%M %p')

In [9]:
order_items_df.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,shipping_limit_time
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19,58.90,13.29,09:45 AM
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03,239.90,19.93,11:05 AM
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18,199.00,17.87,02:48 PM
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15,12.99,12.79,10:10 AM
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13,199.90,18.14,01:57 PM
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23,21.90,12.69,03:55 AM
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14,19.90,11.85,12:10 PM
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10,810.00,70.75,12:30 PM
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26,145.95,11.65,06:31 PM
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06,53.99,11.40,02:10 PM

In [10]:
import pandas as pd
pd.set_option('display.max_columns', None)
order_items_df.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,shipping_limit_time
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19,58.90,13.29,09:45 AM
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03,239.90,19.93,11:05 AM
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18,199.00,17.87,02:48 PM
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15,12.99,12.79,10:10 AM
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13,199.90,18.14,01:57 PM
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23,21.90,12.69,03:55 AM
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14,19.90,11.85,12:10 PM
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10,810.00,70.75,12:30 PM
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26,145.95,11.65,06:31 PM
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06,53.99,11.40,02:10 PM

In [11]:
pd.DataFrame({
    'column': order_items_df.columns,
    'dtype': order_items_df.dtypes.values
})

                column    dtype
0             order_id      str
1        order_item_id    int64
2           product_id      str
3            seller_id      str
4  shipping_limit_date   object
5                price  float64
6        freight_value  float64
7  shipping_limit_time      str

In [13]:
order_items_df['shipping_limit_date'] = pd.to_datetime(
    order_items_df['shipping_limit_date'],
    errors='coerce'
).dt.date

In [14]:
order_items_df[['shipping_limit_date']].head(10)

  shipping_limit_date
0          2017-09-19
1          2017-05-03
2          2018-01-18
3          2018-08-15
4          2017-02-13
5          2017-05-23
6          2017-12-14
7          2018-07-10
8          2018-03-26
9          2018-07-06

In [15]:
type(order_items_df['shipping_limit_date'].iloc[0])

datetime.date

In [19]:
# Show dtypes
print(order_items_df.dtypes)

# Show first 10 rows with all columns
pd.set_option('display.max_columns', None)
display(order_items_df.head(10))

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date     object
price                  float64
freight_value          float64
shipping_limit_time        str
dtype: object

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,shipping_limit_time
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19,58.90,13.29,09:45 AM
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03,239.90,19.93,11:05 AM
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18,199.00,17.87,02:48 PM
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15,12.99,12.79,10:10 AM
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13,199.90,18.14,01:57 PM
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23,21.90,12.69,03:55 AM
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14,19.90,11.85,12:10 PM
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10,810.00,70.75,12:30 PM
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26,145.95,11.65,06:31 PM
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06,53.99,11.40,02:10 PM

In [20]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

order_items_df.to_csv(os.path.join(save_path, "order_items.csv"), index=False)

print("Saved as D:\\Olist Clean\\order_items.csv")

Saved as D:\Olist Clean\order_items.csv

<p style="font-size:24px; font-weight:bold;">Olist Payment Analysis</p>

In [21]:
import pandas as pd

payments_df = pd.read_csv("olist_order_payments_dataset.csv")

payments_df.head(10)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12
6,771ee386b001f06208a7419e4fc1bbd7,1,credit_card,1,81.16
7,3d7239c394a212faae122962df514ac7,1,credit_card,3,51.84
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09
9,0573b5e23cbd798006520e1d5b4c6714,1,boleto,1,51.95

In [22]:
print("Dtypes:")
print(payments_df.dtypes)


print("\nMissing values:")
print(payments_df.isnull().sum())

payments_df['payment_value_num'] = pd.to_numeric(payments_df['payment_value'], errors='coerce')
payments_df['payment_installments_num'] = pd.to_numeric(payments_df['payment_installments'], errors='coerce')

print("\nNon-numeric payment_value:", payments_df['payment_value_num'].isna().sum())
print("Non-numeric payment_installments:", payments_df['payment_installments_num'].isna().sum())

messy_payment_type = payments_df[
    payments_df['payment_type'].astype(str).str.contains(r'[^a-zA-Z_]', regex=True, na=False)
]['payment_type'].drop_duplicates()

print("\nMessy payment_type values:")
display(messy_payment_type)

payments_df.drop(columns=['payment_value_num', 'payment_installments_num'], inplace=True, errors='ignore')

Dtypes:
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

Missing values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Non-numeric payment_value: 0
Non-numeric payment_installments: 0

Messy payment_type values:

Series([], Name: payment_type, dtype: str)

In [24]:
payments_df['payment_type'].value_counts()
payments_df['payment_type'].value_counts().reset_index().rename(
    columns={'index': 'payment_type', 'payment_type': 'count'}
)

         count  count
0  credit_card  76795
1       boleto  19784
2      voucher   5775
3   debit_card   1529
4  not_defined      3

In [25]:
payments_df['payment_type'] = payments_df['payment_type'].astype(str).str.strip()

payments_df['payment_type'] = payments_df['payment_type'].replace({
    'not_defined': 'Others Method',
    'credit_card': 'Credit Card',
    'boleto': 'Boleto',
    'voucher': 'Voucher',
    'debit_card': 'Debit Card'
})

In [26]:
payments_df['payment_type'].value_counts()

payment_type
Credit Card      76795
Boleto           19784
Voucher           5775
Debit Card        1529
Others Method        3
Name: count, dtype: int64

In [27]:
pd.set_option('display.max_columns', None)
payments_df.head(10)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,Credit Card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,Credit Card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,Credit Card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,Credit Card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,Credit Card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,Credit Card,2,96.12
6,771ee386b001f06208a7419e4fc1bbd7,1,Credit Card,1,81.16
7,3d7239c394a212faae122962df514ac7,1,Credit Card,3,51.84
8,1f78449c87a54faf9e96e88ba1491fa9,1,Credit Card,6,341.09
9,0573b5e23cbd798006520e1d5b4c6714,1,Boleto,1,51.95

In [28]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

payments_df.to_csv(os.path.join(save_path, "Payments.csv"), index=False)

print("Saved as D:\\Olist Clean\\Payments.csv")

Saved as D:\Olist Clean\Payments.csv

<p style="font-size:24px; font-weight:bold;">Olist Order Reviews</p>

In [29]:
import pandas as pd

reviews_df = pd.read_csv("olist_order_reviews_dataset.csv")

reviews_df.head(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,NaN,NaN,2018-04-13 00:00:00,2018-04-16 00:39:37
6,07f9bee5d1b850860defd761afa7ff16,e48aa0d2dcec3a2e87348811bcfdf22b,5,NaN,NaN,2017-07-16 00:00:00,2017-07-18 19:30:34
7,7c6400515c67679fbee952a7525281ef,c31a859e34e3adac22f376954e19b39d,5,NaN,NaN,2018-08-14 00:00:00,2018-08-14 21:36:06
8,a3f6f7f6f433de0aefbb97da197c554c,9c214ac970e84273583ab523dfafd09b,5,NaN,NaN,2017-05-17 00:00:00,2017-05-18 12:05:37
9,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47

In [ ]:
print("Dtypes:")
print(reviews_df.dtypes)

print("\nMissing values:")
print(reviews_df.isnull().sum())

messy_title = reviews_df[
    reviews_df['review_comment_title'].astype(str).str.contains(r'[^A-Za-zÀ-ÿ0-9\s]', regex=True, na=False)
]['review_comment_title'].drop_duplicates()

messy_message = reviews_df[
    reviews_df['review_comment_message'].astype(str).str.contains(r'[^A-Za-zÀ-ÿ0-9\s]', regex=True, na=False)
]['review_comment_message'].drop_duplicates()

print("\nMessy review_comment_title values:")
display(messy_title)

print("\nMessy review_comment_message values:")
display(messy_message)

Dtypes:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

Missing values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Messy review_comment_title values:

34                Muito bom.
38              Maravilhoso!
67           Ótimo Produto!
79        RECOMENDO SEMPRE!!
90           ***** Recomendo
                ...
98706        Sim, recomendo!
98771           Produto bom.
98780            Obrigada!!!
98885    Pruto muito frágil.
99187           Nota máxima!
Name: review_comment_title, Length: 1024, dtype: str

Messy review_comment_message values:

3                    Recebi bem antes do prazo estipulado.
9        aparelho eficiente. no site a marca do aparelh...
12         Mas um pouco ,travando...pelo valor ta Boa.\r\n
15       Vendedor confiável, produto ok e entrega antes...
16       GOSTARIA DE SABER O QUE HOUVE, SEMPRE RECEBI E...
                               ...
99205    para este produto recebi de acordo com a compr...
99208    Entregou dentro do prazo. O produto chegou em ...
99215    O produto não foi enviado com NF, não existe v...
99221    Excelente mochila, entrega super rápida. Super...
99223    meu produto chegou e ja tenho que devolver, po...
Name: review_comment_message, Length: 27873, dtype: str

In [31]:
reviews_df[reviews_df['review_score'] > 5]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [32]:
(reviews_df['review_score'] > 5).sum()

np.int64(0)

In [33]:
reviews_df['review_comment_message'] = reviews_df['review_comment_message'].fillna('No message')
reviews_df['review_comment_title'] = reviews_df['review_comment_title'].fillna('No Title')

In [34]:
reviews_df[['review_comment_title', 'review_comment_message']].head(10)

  review_comment_title                             review_comment_message
0             No Title                                         No message
1             No Title                                         No message
2             No Title                                         No message
3             No Title              Recebi bem antes do prazo estipulado.
4             No Title  Parabéns lojas lannister adorei comprar pela I...
5             No Title                                         No message
6             No Title                                         No message
7             No Title                                         No message
8             No Title                                         No message
9            recomendo  aparelho eficiente. no site a marca do aparelh...

In [ ]:
dt = pd.to_datetime(reviews_df['review_creation_date'], errors='coerce')

reviews_df['review_creation_date'] = dt.dt.date

reviews_df['review_creation_time'] = dt.dt.strftime('%I:%M %p')

In [36]:
reviews_df['review_creation_time'] = pd.to_datetime(
    reviews_df['review_creation_time'],
    format='%I:%M %p',
    errors='coerce'
).dt.time

In [ ]:
dt = pd.to_datetime(reviews_df['review_answer_timestamp'], errors='coerce')

reviews_df['review_answer_timestamp'] = dt.dt.date

reviews_df['review_answer_time'] = dt.dt.strftime('%I:%M %p')

In [38]:
reviews_df['review_answer_time'] = pd.to_datetime(
    reviews_df['review_answer_time'],
    format='%I:%M %p',
    errors='coerce'
).dt.time

In [39]:
pd.DataFrame({
    'column': reviews_df.columns,
    'dtype': reviews_df.dtypes.values
})

                    column   dtype
0                review_id     str
1                 order_id     str
2             review_score   int64
3     review_comment_title     str
4   review_comment_message     str
5     review_creation_date  object
6  review_answer_timestamp  object
7     review_creation_time  object
8       review_answer_time  object

In [40]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

reviews_df.to_csv(os.path.join(save_path, "Reviews.csv"), index=False)

print("Saved as D:\\Olist Clean\\Reviews.csv")

Saved as D:\Olist Clean\Reviews.csv

<p style="font-size:24px; font-weight:bold;">Olist Orders Analysis</p>

In [41]:
import pandas as pd

orders_df = pd.read_csv("olist_orders_dataset.csv")

orders_df.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00

In [ ]:
# Column types
print("Dtypes:")
print(orders_df.dtypes)

# Null values
print("\nMissing values:")
print(orders_df.isnull().sum())

# Duplicate rows
print("\nDuplicate rows:", orders_df.duplicated().sum())

Dtypes:
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

Missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicate rows: 0

In [43]:
orders_df['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [44]:
orders_df['order_status'] = (
    orders_df['order_status']
    .str.replace('_', ' ', regex=False)
    .str.title()
)

In [45]:
orders_df['order_status'].unique()

<StringArray>
[  'Delivered',    'Invoiced',     'Shipped',  'Processing', 'Unavailable',
    'Canceled',     'Created',    'Approved']
Length: 8, dtype: str

In [ ]:
dt = pd.to_datetime(orders_df['order_purchase_timestamp'], errors='coerce')

orders_df['order_purchase_timestamp'] = dt.dt.date

orders_df['order_purchase_time'] = dt.dt.strftime('%I:%M %p')

In [47]:
orders_df['order_purchase_time'] = pd.to_datetime(
    orders_df['order_purchase_time'],
    format='%I:%M %p',
    errors='coerce'
).dt.time

In [48]:

dt = pd.to_datetime(orders_df['order_approved_at'], errors='coerce')


orders_df['order_approved_at'] = dt.dt.date

orders_df['order_approved_time'] = dt.dt.strftime('%I:%M %p')

In [49]:
orders_df['order_approved_time'] = pd.to_datetime(
    orders_df['order_approved_time'],
    format='%I:%M %p',
    errors='coerce'
).dt.time

In [ ]:
dt = pd.to_datetime(orders_df['order_delivered_carrier_date'], errors='coerce')

orders_df['order_delivered_carrier_date'] = dt.dt.date

orders_df['order_delivered_carrier_time'] = dt.dt.strftime('%I:%M %p')

In [52]:
orders_df['order_delivered_carrier_time'] = pd.to_datetime(
    orders_df['order_delivered_carrier_time'],
    format='%I:%M %p',
    errors='coerce'
).dt.time

In [ ]:
dt = pd.to_datetime(orders_df['order_delivered_customer_date'], errors='coerce')

orders_df['order_delivered_customer_date'] = dt.dt.date

orders_df['order_delivered_customer_time'] = dt.dt.strftime('%I:%M %p')

In [54]:
orders_df['order_delivered_customer_time'] = pd.to_datetime(
    orders_df['order_delivered_customer_time'],
    format='%I:%M %p',
    errors='coerce'
).dt.time

In [55]:
summary = pd.DataFrame({
    'column': orders_df.columns,
    'dtype': orders_df.dtypes.values,
    'example_value': [orders_df[col].dropna().iloc[0] if orders_df[col].notna().any() else None
                      for col in orders_df.columns]
})

summary

                           column   dtype                     example_value
0                        order_id     str  e481f51cbdc54678b7cc49136f2d6af7
1                     customer_id     str  9ef432eb6251297304e76186b10a928d
2                    order_status     str                         Delivered
3        order_purchase_timestamp  object                        2017-10-02
4               order_approved_at  object                        2017-10-02
5    order_delivered_carrier_date  object                        2017-10-04
6   order_delivered_customer_date  object                        2017-10-10
7   order_estimated_delivery_date     str               2017-10-18 00:00:00
8             order_purchase_time  object                          10:56:00
9             order_approved_time  object                          11:07:00
10   order_delivered_carrier_time  object                          00:00:00
11  order_delivered_customer_time  object                          21:25:00

In [58]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

orders_df.to_csv(os.path.join(save_path, "Orders.csv"), index=False)

print("Saved as D:\\Olist Clean\\Orders.csv")

Saved as D:\Olist Clean\Orders.csv

<p style="font-size:24px; font-weight:bold;">Olist Product Analysis</p>

In [59]:
import pandas as pd

products_df = pd.read_csv("olist_products_dataset.csv")

products_df.head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0

In [69]:
print("Duplicate rows:", products_df.duplicated().sum())

print("\nMissing values:")
print(products_df.isnull().sum())

text_cols = products_df.select_dtypes(include='object').columns

for col in text_cols:
    messy = products_df[
        products_df[col].astype(str).str.contains(r'[^A-Za-zÀ-ÿ0-9_\s]', regex=True, na=False)
    ][col].drop_duplicates()
    
    print(f"\nMessy values in {col}: {len(messy)}")
    if len(messy) > 0:
        display(messy)

Duplicate rows: 0

Missing values:
product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

Messy values in product_id: 0

Messy values in product_category_name: 0

C:\Users\England\AppData\Local\Temp\ipykernel_19188\357537188.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = products_df.select_dtypes(include='object').columns

In [62]:
products_df['product_category_name'] = products_df['product_category_name'].fillna('Unknown')
products_df['product_category_name'].isna().sum()

np.int64(0)

In [63]:
products_df['product_id'].nunique()

32951

In [64]:
print("Unique product_id:", products_df['product_id'].nunique())

Unique product_id: 32951

In [70]:
import pandas as pd
pd.set_option('display.max_columns', None)

products_df.head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0

In [66]:
products_df['product_category_name'].dropna().unique()

<StringArray>
[                                    'perfumaria',
                                          'artes',
                                  'esporte_lazer',
                                          'bebes',
                          'utilidades_domesticas',
                          'instrumentos_musicais',
                                     'cool_stuff',
                               'moveis_decoracao',
                               'eletrodomesticos',
                                     'brinquedos',
                                'cama_mesa_banho',
               'construcao_ferramentas_seguranca',
                         'informatica_acessorios',
                                   'beleza_saude',
                               'malas_acessorios',
                             'ferramentas_jardim',
                              'moveis_escritorio',
                                     'automotivo',
                                    'eletronicos',
                               'fashion_calcados',
                                      'telefonia',
                                      'papelaria',
                    'fashion_bolsas_e_acessorios',
                                            'pcs',
                                'casa_construcao',
                             'relogios_presentes',
              'construcao_ferramentas_construcao',
                                       'pet_shop',
                                'eletroportateis',
                      'agro_industria_e_comercio',
                                        'Unknown',
                                    'moveis_sala',
                        'sinalizacao_e_seguranca',
                                   'climatizacao',
                                 'consoles_games',
                         'livros_interesse_geral',
             'construcao_ferramentas_ferramentas',
                 'fashion_underwear_e_moda_praia',
                        'fashion_roupa_masculina',
 'moveis_cozinha_area_de_servico_jantar_e_jardim',
                  'industria_comercio_e_negocios',
                                 'telefonia_fixa',
              'construcao_ferramentas_iluminacao',
                                'livros_tecnicos',
                             'eletrodomesticos_2',
                              'artigos_de_festas',
                                        'bebidas',
                                   'market_place',
                                     'la_cuisine',
                  'construcao_ferramentas_jardim',
                         'fashion_roupa_feminina',
                                  'casa_conforto',
                                          'audio',
                              'alimentos_bebidas',
                                         'musica',
                                      'alimentos',
                       'tablets_impressao_imagem',
                              'livros_importados',
                    'portateis_casa_forno_e_cafe',
                                'fashion_esporte',
                               'artigos_de_natal',
                  'fashion_roupa_infanto_juvenil',
                                   'dvds_blu_ray',
                             'artes_e_artesanato',
                                       'pc_gamer',
                                  'moveis_quarto',
                                      'cine_foto',
                                'fraldas_higiene',
                                         'flores',
                                'casa_conforto_2',
  'portateis_cozinha_e_preparadores_de_alimentos',
                             'seguros_e_servicos',
                      'moveis_colchao_e_estofado',
                              'cds_dvds_musicais']
Length: 74, dtype: str

In [67]:
cols_to_zero = [
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]

products_df[cols_to_zero] = products_df[cols_to_zero].fillna(0)

In [71]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

products_df.to_csv(os.path.join(save_path, "Products.csv"), index=False)

print("Saved as D:\\Olist Clean\\Products.csv")

Saved as D:\Olist Clean\Products.csv

<p style="font-size:24px; font-weight:bold;">Olist Sellers Analysis</p>

In [1]:
import pandas as pd

sellers_df = pd.read_csv("olist_sellers_dataset.csv")

sellers_df.head(10)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
5,c240c4061717ac1806ae6ee72be3533b,20920,rio de janeiro,RJ
6,e49c26c3edfa46d227d5121a6b6e4d37,55325,brejao,PE
7,1b938a7ec6ac5061a66a3766e0e75f90,16304,penapolis,SP
8,768a86e36ad6aae3d03ee3c6433d61df,1529,sao paulo,SP
9,ccc4bbb5f32a6ab2b7066a4130f114e3,80310,curitiba,PR

In [ ]:
print("Rows, Columns:", sellers_df.shape)

print("\nMissing values:")
print(sellers_df.isnull().sum())

print("\nDuplicate rows:", sellers_df.duplicated().sum())

Rows, Columns: (3095, 4)

Missing values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Duplicate rows: 0

In [3]:
print("Total city values:", sellers_df['seller_city'].count())
print("Total unique cities:", sellers_df['seller_city'].nunique())

unique_cities = sellers_df['seller_city'].dropna().drop_duplicates().sort_values()
display(unique_cities)

messy_cities = sellers_df[
    sellers_df['seller_city'].str.contains(r'[^A-Za-zÀ-ÿ\s]', regex=True, na=False)
]['seller_city'].drop_duplicates().sort_values()

print("Messy city names:", len(messy_cities))
display(messy_cities)

Total city values: 3095
Total unique cities: 611

517            04482255
2067    abadia de goias
2153     afonso claudio
2589    aguas claras df
2115           alambari
             ...
513       volta redonda
452          votorantim
746         votuporanga
2472            xanxere
2352              xaxim
Name: seller_city, Length: 611, dtype: str

Messy city names: 28

517                                     04482255
1610                                   andira-pr
874               arraial d'ajuda (porto seguro)
237                                 auriflama/sp
1447                     barbacena/ minas gerais
2162                     carapicuiba / sao paulo
622                               cariacica / es
3015                         jacarei / sao paulo
78                                    lages - sc
1159                              maua/sao paulo
1337                        mogi das cruzes / sp
551     novo hamburgo, rio grande do sul, brasil
1712                                  pinhais/pr
1920                  ribeirao preto / sao paulo
1649             rio de janeiro / rio de janeiro
1346              rio de janeiro \rio de janeiro
2988      rio de janeiro, rio de janeiro, brasil
1890                       santa barbara d'oeste
476                        santa barbara d´oeste
945                        santo andre/sao paulo
707                           sao miguel d'oeste
826                               sao paulo - sp
246                        sao paulo / sao paulo
2620                   sao sebastiao da grama/sp
360                                   são paulo
869                                       sbc/sp
1004                                     sp / sp
2258                   vendas@creditparts.com.br
Name: seller_city, dtype: str

In [4]:
sellers_df['seller_city'] = sellers_df['seller_city'].replace({'04482255': 'São Paulo'})

In [ ]:
import re

sellers_df['seller_city'] = sellers_df['seller_city'].str.lower().str.strip()

sellers_df['seller_city'] = sellers_df['seller_city'].apply(
    lambda x: re.split('/|-|,', str(x))[0].strip()
)

sellers_df['seller_city'] = sellers_df['seller_city'].str.replace(r"\(.*?\)", "", regex=True).str.strip()

sellers_df['seller_city'] = sellers_df['seller_city'].replace('04482255', 'sao paulo')

sellers_df['seller_city'] = sellers_df['seller_city'].str.title()

In [6]:
messy_cities = sellers_df[
    sellers_df['seller_city'].str.contains(r'[^A-Za-zÀ-ÿ\s]', regex=True, na=False)
]['seller_city'].drop_duplicates().sort_values()

print("Messy city names:", len(messy_cities))
display(messy_cities)

Messy city names: 7

874                    Arraial D'Ajuda
1346    Rio De Janeiro \Rio De Janeiro
1890             Santa Barbara D'Oeste
476              Santa Barbara D´Oeste
707                 Sao Miguel D'Oeste
360                         SãO Paulo
2258         Vendas@Creditparts.Com.Br
Name: seller_city, dtype: str

In [7]:
import pandas as pd
import unicodedata

def remove_accents(text):
    text = str(text)
    return ''.join(
        ch for ch in unicodedata.normalize('NFKD', text)
        if not unicodedata.combining(ch)
    )
sellers_df['seller_city'] = sellers_df['seller_city'].str.lower().str.strip()

sellers_df['seller_city'] = sellers_df['seller_city'].apply(remove_accents)

sellers_df['seller_city'] = sellers_df['seller_city'].replace({
    'vendas@creditparts.com.br': 'indaiatuba',
    "santa barbara d´oeste": "santa barbara d'oeste",
    'rio de janeiro \\rio de janeiro': 'rio de janeiro'
})

sellers_df['seller_city'] = sellers_df['seller_city'].str.split('\\').str[0].str.split('/').str[0].str.strip()

In [8]:
messy_cities = sellers_df[
    sellers_df['seller_city'].str.contains(r'[^A-Za-z\s]', regex=True, na=False)
]['seller_city'].drop_duplicates().sort_values()

print("Messy city names:", len(messy_cities))
display(messy_cities)

Messy city names: 3

874           arraial d'ajuda
1890    santa barbara d'oeste
707        sao miguel d'oeste
Name: seller_city, dtype: str

In [9]:
sellers_df['seller_city'].drop_duplicates().sort_values().head(20)

2067         abadia de goias
2153          afonso claudio
2589         aguas claras df
2115                alambari
1277                 alfenas
1561     almirante tamandare
2478         alvares machado
2867                alvorada
271                americana
1200                  amparo
781                   ampere
10                  anapolis
1610                  andira
1656                andradas
1008          angra dos reis
1686       angra dos reis rj
1728    ao bernardo do campo
2043               aparecida
3052    aparecida de goiania
597                  aperibe
Name: seller_city, dtype: str

In [11]:
import pandas as pd
import re

sellers_df['seller_city'] = sellers_df['seller_city'].str.lower().str.strip()

states = [' rj', ' sp', ' mg', ' pr', ' sc', ' rs', ' df', ' go', ' es']
for state in states:
    sellers_df['seller_city'] = sellers_df['seller_city'].str.replace(fr'{state}$', '', regex=True).str.strip()

sellers_df['seller_city'] = sellers_df['seller_city'].replace('ao bernardo do campo', 'sao bernardo do campo')

sellers_df['seller_city'] = sellers_df['seller_city'].str.replace(r'\s+', ' ', regex=True)

In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)
sellers_df.head(20)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
5,c240c4061717ac1806ae6ee72be3533b,20920,rio de janeiro,RJ
6,e49c26c3edfa46d227d5121a6b6e4d37,55325,brejao,PE
7,1b938a7ec6ac5061a66a3766e0e75f90,16304,penapolis,SP
8,768a86e36ad6aae3d03ee3c6433d61df,1529,sao paulo,SP
9,ccc4bbb5f32a6ab2b7066a4130f114e3,80310,curitiba,PR
10,8cb7c5ddf41f4d506eba76e9a4702a25,75110,anapolis,GO
11,a7a9b880c49781da66651ccf4ba9ac38,13530,itirapina,SP
12,8bd0f31cf0a614c658f6763bd02dea69,1222,sao paulo,SP
13,05a48cc8859962767935ab9087417fbb,5372,sao paulo,SP
14,7b8e8ec35bad4b0ef7e3963650b0a87b,88705,tubarao,SC
15,1444c08e64d55fb3c25f0f09c07ffcf2,42738,lauro de freitas,BA
16,166e8f1381e09651983c38b1f6f91c11,88780,imbituba,SC
17,e38db885400cd35c71dfd162f2c1dbcf,70740,brasilia,DF
18,d2e753bb80b7d4faa77483ed00edc8ca,45810,porto seguro,BA
19,f9ec7093df3a7b346b7bcf7864069ca3,5138,sao paulo,SP

In [13]:
messy_cities = sellers_df[
    sellers_df['seller_city'].str.contains(r'[^A-Za-z\s]', regex=True, na=False)
]['seller_city'].drop_duplicates().sort_values()

print("Messy city names:", len(messy_cities))
display(messy_cities)

Messy city names: 3

874           arraial d'ajuda
1890    santa barbara d'oeste
707        sao miguel d'oeste
Name: seller_city, dtype: str

In [14]:
messy_cities = sellers_df[
    sellers_df['seller_city'].str.contains(r"[^A-Za-z\s']", regex=True, na=False)
]['seller_city'].drop_duplicates().sort_values()

print("Messy city names:", len(messy_cities))
display(messy_cities)

Messy city names: 0

Series([], Name: seller_city, dtype: object)

In [15]:
messy_states = sellers_df[
    ~sellers_df['seller_state'].str.fullmatch(r'[A-Z]{2}', na=False)
]['seller_state'].drop_duplicates().sort_values()

print("Messy seller_state values:", len(messy_states))
display(messy_states)

Messy seller_state values: 0

Series([], Name: seller_state, dtype: str)

In [16]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

sellers_df.to_csv(os.path.join(save_path, "Sellers.csv"), index=False)

print("Saved as D:\\Olist Clean\\Sellers.csv")

Saved as D:\Olist Clean\Sellers.csv

<p style="font-size:24px; font-weight:bold;">Olist Product Category</p>

In [ ]:
import pandas as pd

category_df = pd.read_csv("product_category_name_translation.csv")

print("Total rows:", category_df.shape[0])

print("Unique Portuguese categories:", category_df['product_category_name'].nunique())
print("Unique English categories:", category_df['product_category_name_english'].nunique())

print("\nMissing values:")
print(category_df.isnull().sum())

print("\nDuplicate rows:", category_df.duplicated().sum())

text_cols = category_df.select_dtypes(include='object').columns
for col in text_cols:
    messy = category_df[
        category_df[col].astype(str).str.contains(r'[^A-Za-zÀ-ÿ0-9_\s]', regex=True, na=False)
    ][col].drop_duplicates().sort_values()

    print(f"\nMessy values in {col}: {len(messy)}")
    if len(messy) > 0:
        display(messy)

Total rows: 71
Unique Portuguese categories: 71
Unique English categories: 71

Missing values:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicate rows: 0

Messy values in product_category_name: 0

Messy values in product_category_name_english: 0

C:\Users\England\AppData\Local\Temp\ipykernel_9856\1339535585.py:20: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = category_df.select_dtypes(include='object').columns

In [4]:
pd.set_option('display.max_columns', None)
category_df.head(20)

          product_category_name product_category_name_english
0                  beleza_saude                 health_beauty
1        informatica_acessorios         computers_accessories
2                    automotivo                          auto
3               cama_mesa_banho                bed_bath_table
4              moveis_decoracao               furniture_decor
5                 esporte_lazer                sports_leisure
6                    perfumaria                     perfumery
7         utilidades_domesticas                    housewares
8                     telefonia                     telephony
9            relogios_presentes                 watches_gifts
10            alimentos_bebidas                    food_drink
11                        bebes                          baby
12                    papelaria                    stationery
13     tablets_impressao_imagem        tablets_printing_image
14                   brinquedos                          toys
15               telefonia_fixa               fixed_telephony
16           ferramentas_jardim                  garden_tools
17  fashion_bolsas_e_acessorios      fashion_bags_accessories
18              eletroportateis              small_appliances
19               consoles_games                consoles_games

In [5]:
import re

category_df['product_category_name_english'] = (
    category_df['product_category_name_english']
    .astype(str)
    .str.replace(r'[^A-Za-z\s]', ' ', regex=True)  
    .str.replace(r'\s+', ' ', regex=True)          
    .str.strip()
    .str.title()
)

In [6]:
pd.set_option('display.max_columns', None)
category_df.head(20)

          product_category_name product_category_name_english
0                  beleza_saude                 Health Beauty
1        informatica_acessorios         Computers Accessories
2                    automotivo                          Auto
3               cama_mesa_banho                Bed Bath Table
4              moveis_decoracao               Furniture Decor
5                 esporte_lazer                Sports Leisure
6                    perfumaria                     Perfumery
7         utilidades_domesticas                    Housewares
8                     telefonia                     Telephony
9            relogios_presentes                 Watches Gifts
10            alimentos_bebidas                    Food Drink
11                        bebes                          Baby
12                    papelaria                    Stationery
13     tablets_impressao_imagem        Tablets Printing Image
14                   brinquedos                          Toys
15               telefonia_fixa               Fixed Telephony
16           ferramentas_jardim                  Garden Tools
17  fashion_bolsas_e_acessorios      Fashion Bags Accessories
18              eletroportateis              Small Appliances
19               consoles_games                Consoles Games

In [7]:
import os

save_path = r"D:\Olist Clean"
os.makedirs(save_path, exist_ok=True)

category_df.to_csv(os.path.join(save_path, "Product Name.csv"), index=False)

print("Saved as D:\\Olist Clean\\Product Name.csv")

Saved as D:\Olist Clean\Product Name.csv